# Generated by Django 4.1.6 on 2023-02-13 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
                ('color', models.CharField(max_length=10)),
                ('detail', models.TextField(max_length=100)),
                ('featured', models.BooleanField()),
                ('slug', models.SlugField()),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='karl_products.category')),
            ],
        ),
    ]
