# Generated by Django 4.1.6 on 2023-02-14 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karl_products', '0002_category_slug_alter_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
