# Generated by Django 4.1.6 on 2023-02-14 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('karl_products', '0004_alter_product_detail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
