# Generated by Django 4.1.6 on 2023-02-14 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karl_products', '0005_remove_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='static/img/product-img/product-1.jpg', upload_to='static/img/product-img/'),
        ),
    ]
