# Generated by Django 4.1.6 on 2023-02-19 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karl_products', '0008_alter_product_category_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='image',
            field=models.ImageField(upload_to='hello/'),
        ),
    ]
