# Generated by Django 4.1.6 on 2023-02-19 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karl_products', '0009_alter_review_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='image',
            field=models.ImageField(upload_to='static/img/product-img/'),
        ),
    ]
