# Generated by Django 4.1.6 on 2023-02-23 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('karl_products', '0011_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cart',
        ),
    ]
