# Generated by Django 4.1.6 on 2023-02-26 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('karl_products', '0013_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cart',
        ),
    ]
